INSERT INTO milestone.HealthInfo (HealthInfoID, QuestionnaireResponses, MedicalAlerts, GuestID)
VALUES
(1, 'No known conditions, non-smoker, walks regularly', 'None', 1),
(2, 'Mild asthma, uses rescue inhaler, exercises occasionally', 'Asthma inhaler', 2),
(3, 'Type 2 diabetes, low-carb diet, monitors blood sugar', 'Insulin', 3),
(4, 'High blood pressure, avoids caffeine, takes meds', 'Lisinopril', 4),
(5, 'Recovering from ankle surgery, limited mobility', 'Pain meds', 5),
(6, 'Vegetarian, non-smoker, no alcohol', 'None', 6),
(7, 'Smoker, drinks socially, no major conditions', 'None', 7),
(8, 'History of migraines, sensitive to light/sound', 'Sumatriptan', 8),
(9, 'No exercise routine, eats a high-fat diet', 'None', 9),
(10, 'Low sodium diet, non-smoker, light yoga', 'None', 10),
(11, 'Recovering from flu, under medication', 'Antiviral meds', 11),
(12, 'High cholesterol, daily statin, occasional walking', 'Atorvastatin', 12),
(13, 'No known allergies, healthy diet, active lifestyle', 'None', 13),
(14, 'Vegetarian, occasional swimmer, lactose intolerant', 'None', 14),
(15, 'Recent back surgery, uses wheelchair', 'Painkillers', 15),
(16, 'Gluten intolerant, follows strict diet', 'None', 16),
(17, 'Non-smoker, no chronic issues, moderate exercise', 'None', 17),
(18, 'Asthmatic, avoids pollen-heavy environments', 'Inhaler', 18),
(19, 'Pre-diabetic, under dietician supervision', 'None', 19),
(20, 'History of epilepsy, carries emergency meds', 'Anticonvulsants', 20),
(21, 'Mild hypertension, managed with exercise', 'None', 21),
(22, 'Pregnant, second trimester', 'Prenatal vitamins', 22),
(23, 'Smoker, high stress job, no meds', 'None', 23),
(24, 'Allergic to shellfish, carries EpiPen', 'Epinephrine', 24),
(25, 'Non-smoker, high energy lifestyle', 'None', 25),
(26, 'Recently recovered from pneumonia', 'None', 26),
(27, 'Gluten and dairy free diet', 'None', 27),
(28, 'Mild arthritis in knees, uses braces', 'NSAIDs', 28),
(29, 'Non-smoker, drinks occasionally, no conditions', 'None', 29),
(30, 'Chronic fatigue, under evaluation', 'None', 30),
(31, 'Uses CPAP for sleep apnea', 'CPAP device', 31),
(32, 'Regular yoga, pescatarian, no meds', 'None', 32),
(33, 'Recently diagnosed with anemia', 'Iron supplements', 33),
(34, 'Smoker, frequent headaches', 'None', 34),
(35, 'Mild skin allergies, uses antihistamines', 'Antihistamines', 35),
(36, 'Type 1 diabetes, insulin pump user', 'Insulin', 36),
(37, 'Allergic to latex, avoids rubber products', 'None', 37),
(38, 'Recovering from minor heart procedure', 'Beta blockers', 38),
(39, 'High stress levels, non-smoker, meditation practice', 'None', 39),
(40, 'Vegetarian, low blood pressure', 'None', 40),
(41, 'Non-smoker, avoids gluten, drinks rarely', 'None', 41),
(42, 'Smoker, suffers from acid reflux', 'Antacids', 42),
(43, 'Mild scoliosis, under physical therapy', 'None', 43),
(44, 'Regular runner, no known issues', 'None', 44),
(45, 'Lactose intolerance, carries enzyme pills', 'Lactaid', 45),
(46, 'History of kidney stones, drinks extra water', 'None', 46),
(47, 'Chronic dry eyes, uses drops daily', 'Eye drops', 47),
(48, 'Non-smoker, pescatarian, stress-prone', 'None', 48),
(49, 'Mild eczema, uses topical creams', 'Corticosteroids', 49),
(50, 'Smoker, former alcoholic, sober 6 months', 'None', 50),
(51, 'Vegan, iron deficiency', 'Supplements', 51),
(52, 'History of panic attacks, avoids caffeine', 'None', 52),
(53, 'Mild hearing loss, uses hearing aids', 'None', 53),
(54, 'Non-smoker, high blood pressure', 'Amlodipine', 54),
(55, 'Asthma and peanut allergy', 'Inhaler, EpiPen', 55),
(56, 'On blood thinners, recovering from stroke', 'Warfarin', 56),
(57, 'Gluten-free, non-smoker, mild depression', 'SSRIs', 57),
(58, 'Vegan, runs marathons, takes B12', 'None', 58),
(59, 'Non-smoker, occasional wine, no major health issues', 'None', 59),
(60, 'Smoker, high stress job, recently started therapy', 'None', 60),
(61, 'Diabetic, vegetarian, yoga practitioner', 'Metformin', 61),
(62, 'Non-smoker, drinks tea daily, healthy heart', 'None', 62),
(63, 'Chronic bronchitis, under medication', 'Bronchodilators', 63),
(64, 'No medical issues, daily walks', 'None', 64),
(65, 'Overweight, under nutrition plan', 'None', 65),
(66, 'Type 2 diabetes and hypertension', 'Metformin, Lisinopril', 66),
(67, 'Non-smoker, pescatarian', 'None', 67),
(68, 'Recovering from ACL surgery', 'Painkillers', 68),
(69, 'Seasonal allergies, uses nasal spray', 'Antihistamines', 69),
(70, 'Heart condition, pacemaker installed', 'Blood thinners', 70),
(71, 'Iron deficiency anemia', 'Iron supplements', 71),
(72, 'No major health concerns', 'None', 72),
(73, 'History of gallbladder issues', 'None', 73),
(74, 'Low sugar diet, diabetic', 'Insulin', 74),
(75, 'High cholesterol, avoids fried foods', 'Statins', 75),
(76, 'Mild depression, on treatment', 'SSRIs', 76),
(77, 'Smoker, frequent traveler', 'None', 77),
(78, 'Chronic lower back pain', 'Physical therapy', 78),
(79, 'Pregnant, under doctor care', 'Prenatal supplements', 79),
(80, 'Recovering from COVID-19', 'None', 80),
(81, 'History of seizures, monitored', 'Anticonvulsants', 81),
(82, 'Gluten-free, runs 5k weekly', 'None', 82),
(83, 'Mild anxiety, meditation therapy', 'None', 83),
(84, 'Recent weight loss surgery', 'Vitamin supplements', 84),
(85, 'No conditions, vegetarian, swimmer', 'None', 85),
(86, 'Alcohol allergy, avoids all spirits', 'None', 86),
(87, 'History of heart murmur', 'Monitored', 87),
(88, 'Regular yoga and pilates', 'None', 88),
(89, 'Vegan, has asthma', 'Inhaler', 89),
(90, 'Hypertension, follows DASH diet', 'Beta blockers', 90),
(91, 'Non-smoker, caffeine-free', 'None', 91),
(92, 'Low iron, under dietary monitoring', 'Supplements', 92),
(93, 'Asthmatic, avoids dust-prone areas', 'Inhaler', 93),
(94, 'Allergic to penicillin', 'Avoid antibiotics', 94),
(95, 'High blood sugar, borderline diabetic', 'None', 95),
(96, 'Wears hearing aids, no other issues', 'None', 96),
(97, 'Non-smoker, regular cyclist', 'None', 97),
(98, 'Recovering from COVID vaccine reaction', 'Antihistamines', 98),
(99, 'Low thyroid, takes levothyroxine', 'Thyroid meds', 99),
(100, 'Former cancer patient, in remission', 'None', 100);
