INSERT INTO milestone.Preference (PreferenceID, PreferenceType, PDescription, GuestID)
VALUES
  (51, 'Mini-bar', 'Remove alcohol from mini-bar', 51),
  (52, 'Curtains', 'Blackout curtains needed', 52),
  (53, 'Wake-Up Call', 'Daily wake-up call at 6:30 AM', 53),
  (54, 'Toiletries', 'Eco-friendly toiletries preferred', 54),
  (55, 'Pillow Type', 'Prefers memory foam pillows', 55),
  (56, 'Noise Level', 'Quiet room away from elevator', 56),
  (57, 'Dietary', 'Vegetarian meals only', 57),
  (58, 'Room Fridge', 'Mini fridge must be empty for personal items', 58),
  (59, 'Temperature', 'Keep room temperature at 22°C', 59),
  (60, 'Lighting Type', 'Warm LED lighting only', 60),
  (61, 'Floor Level', 'Wants high-floor room with city view', 61),
  (62, 'Room Cleaning', 'Do not disturb until noon', 62),
  (63, 'Bedding', 'Extra blankets requested', 63),
  (64, 'Smoking', 'Non-smoking room only', 64),
  (65, 'Luggage Help', 'Assistance with heavy luggage', 65),
  (66, 'Tech Access', 'Request HDMI cable and power adapters', 66),
  (67, 'Laundry', 'Laundry pickup at 6 PM daily', 67),
  (68, 'Allergies', 'Hypoallergenic bedding needed', 68),
  (69, 'Bath Type', 'Prefers walk-in shower over bathtub', 69),
  (70, 'Bed Type', 'Requests king-size bed', 70),
  (71, 'Check-In Language', 'Prefer communication in Spanish', 71),
  (72, 'Pet-Friendly', 'Will bring a small dog', 72),
  (73, 'Fragrance-Free', 'No air fresheners or scented linens', 73),
  (74, 'Baby Amenities', 'Crib and baby bath required', 74),
  (75, 'Extra Towels', 'Needs 4 bath towels daily', 75),
  (76, 'Dining', 'Table reservation for 2 every evening', 76),
  (77, 'Spa Access', 'Include spa package if available', 77),
  (78, 'Lighting', 'Prefers natural light with big windows', 78),
  (79, 'Anniversary Setup', 'Decorate room for anniversary surprise', 79),
  (80, 'View Preference', 'Ocean view if available', 80),
  (81, 'Fitness', 'Close to gym if possible', 81),
  (82, 'Special Occasion', 'Birthday cake on arrival', 82),
  (83, 'Turn-Down Service', 'Turn-down service at 9 PM', 83),
  (84, 'Room Color', 'Neutral tones preferred (beige/grey)', 84),
  (85, 'Parking', 'Covered parking spot reserved', 85),
  (86, 'Window Type', 'Operable windows requested', 86),
  (87, 'TV Setup', 'Wants Netflix access', 87),
  (88, 'Room Type', 'Prefers deluxe suite with balcony', 88),
  (89, 'Early Check-In', 'Would like to check in by 10 AM', 89),
  (90, 'Workspace', 'Needs desk and office chair', 90),
  (91, 'Daily Newspaper', 'Deliver New York Times to door', 91),
  (92, 'Security', 'Room close to main reception', 92),
  (93, 'Accessibility', 'Requires wheelchair-accessible room', 93),
  (94, 'Coffee Setup', 'Nespresso machine preferred', 94),
  (95, 'Ironing Board', 'Room with iron and board', 95),
  (96, 'Beverage', 'Prefers green tea and bottled water', 96),
  (97, 'Privacy', 'No housekeeping unless requested', 97),
  (98, 'Music', 'Bluetooth speaker available', 98),
  (99, 'Late Check-Out', 'Late check-out requested (2 PM)', 99),
  (100, 'Turn-Down Service', 'Turn-down service at 9 PM', 100);
